"""Assemble verifiable evidence for a single-day stock move.

Everything here is computed from data already in the database or fetched from
SEC EDGAR. Nothing is generated by a language model. The AI layer consumes this
evidence and is instructed not to introduce causes that do not appear in it.
"""

from __future__ import annotations

import logging
import statistics
from dataclasses import dataclass, field
from datetime import date, timedelta
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.entities import Company, EconomicEvent, PriceBar, QuoteSnapshot
from app.services import sec_filings

logger = logging.getLogger(__name__)

# Minimum peers needed before a sector average means anything.
MIN_PEERS = 4


@dataclass
class Evidence:
    kind: str
    title: str
    detail: str
    source: str
    source_url: str | None = None
    numbers: dict[str, Any] = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind,
            "title": self.title,
            "detail": self.detail,
            "source": self.source,
            "source_url": self.source_url,
            "numbers": self.numbers,
        }


def _fmt(pct: float) -> str:
    return f"{pct:+.2f}%"


async def _market_context(db: AsyncSession, ticker: str, sector: str) -> tuple[list[Evidence], dict[str, Any]]:
    """Compare the move against the whole universe and against sector peers."""
    rows = (
        await db.execute(
            select(QuoteSnapshot.ticker, QuoteSnapshot.change_pct, Company.sector, Company.market_cap)
            .join(Company, Company.ticker == QuoteSnapshot.ticker)
        )
    ).all()
    if not rows:
        return [], {}

    all_moves = [r.change_pct for r in rows if r.change_pct is not None]
    peer_moves = [
        r.change_pct
        for r in rows
        if r.sector == sector and r.ticker != ticker and r.change_pct is not None
    ]

    evidence: list[Evidence] = []
    stats: dict[str, Any] = {}

    if all_moves:
        market = statistics.median(all_moves)
        advancers = sum(1 for m in all_moves if m > 0)
        stats["market_median_pct"] = round(market, 3)
        stats["advancers"] = advancers
        stats["decliners"] = len(all_moves) - advancers
        evidence.append(
            Evidence(
                kind="market",
                title=f"The broad market moved {_fmt(market)} today",
                detail=(
                    f"Across {len(all_moves)} S&P 500 names in this database, the median move was "
                    f"{_fmt(market)}, with {advancers} rising and {len(all_moves) - advancers} falling. "
                    "When most of the market moves together, the cause is usually economy-wide news "
                    "rather than anything specific to one company."
                ),
                source="Computed from live Yahoo Finance quotes in this database",
                numbers={"median_pct": round(market, 3), "advancers": advancers, "decliners": len(all_moves) - advancers},
            )
        )

    if len(peer_moves) >= MIN_PEERS:
        peer_median = statistics.median(peer_moves)
        stats["sector_median_pct"] = round(peer_median, 3)
        stats["peer_count"] = len(peer_moves)
        evidence.append(
            Evidence(
                kind="sector",
                title=f"{sector} peers moved {_fmt(peer_median)} today",
                detail=(
                    f"The median move across {len(peer_moves)} other {sector} companies was {_fmt(peer_median)}. "
                    "If this stock and its peers moved together, something affecting the whole industry is "
                    "the more likely explanation."
                ),
                source="Computed from live Yahoo Finance quotes in this database",
                numbers={"median_pct": round(peer_median, 3), "peers": len(peer_moves)},
            )
        )

    return evidence, stats


async def _volatility_context(db: AsyncSession, ticker: str, change_pct: float) -> tuple[Evidence | None, dict[str, Any]]:
    """Is this move actually unusual for this stock, or an ordinary day?"""
    bars = (
        (
            await db.execute(
                select(PriceBar)
                .where(PriceBar.ticker == ticker)
                .order_by(PriceBar.bar_date.desc())
                .limit(130)
            )
        )
        .scalars()
        .all()
    )
    if len(bars) < 25:
        return None, {}

    closes = [b.close for b in reversed(bars)]
    daily = [
        (closes[i] - closes[i - 1]) / closes[i - 1] * 100.0
        for i in range(1, len(closes))
        if closes[i - 1]
    ]
    if len(daily) < 20:
        return None, {}

    sigma = statistics.pstdev(daily)
    if sigma <= 0:
        return None, {}

    z = change_pct / sigma
    typical = statistics.median(abs(d) for d in daily)

    if abs(z) >= 2:
        verdict = "a genuinely big day"
        nuance = "Moves this size usually have a specific trigger worth looking for."
    elif abs(z) >= 1:
        verdict = "a somewhat larger move than usual"
        nuance = "Notable, but not the kind of move that always has a single clean explanation."
    else:
        verdict = "an ordinary day"
        nuance = (
            "Most days like this have no single cause at all — it is just normal trading noise. "
            "Be suspicious of any story that claims otherwise."
        )

    stats = {
        "daily_volatility_pct": round(sigma, 3),
        "z_score": round(z, 2),
        "typical_daily_move_pct": round(typical, 3),
        "sample_days": len(daily),
    }
    return (
        Evidence(
            kind="volatility",
            title=f"This is {verdict} for {ticker}",
            detail=(
                f"Over the last {len(daily)} trading days, {ticker} moved about {typical:.2f}% on a typical day "
                f"(standard deviation {sigma:.2f}%). Today's {_fmt(change_pct)} is {abs(z):.1f} standard "
                f"deviations from flat. {nuance}"
            ),
            source="Computed from daily closes stored in this database",
            numbers=stats,
        ),
        stats,
    )


async def _macro_context(db: AsyncSession, as_of: date) -> list[Evidence]:
    window_start = as_of - timedelta(days=4)
    events = (
        (
            await db.execute(
                select(EconomicEvent)
                .where(EconomicEvent.event_date >= window_start)
                .where(EconomicEvent.event_date <= as_of)
                .order_by(EconomicEvent.event_date.desc())
            )
        )
        .scalars()
        .all()
    )
    return [
        Evidence(
            kind="macro",
            title=f"{event.title} ({event.event_date.isoformat()})",
            detail=event.plain_english,
            source="Economic calendar",
            numbers={"date": event.event_date.isoformat(), "category": event.category},
        )
        for event in events[:3]
    ]


async def _filing_context(ticker: str, as_of: date) -> list[Evidence]:
    """Recent 8-K / 10-Q filings are the most concrete company-specific triggers."""
    try:
        index = await sec_filings.recent_filings(ticker, forms=("8-K", "10-Q", "10-K"), limit=8)
    except sec_filings.SECError as exc:
        logger.info("EDGAR evidence unavailable for %s: %s", ticker, exc)
        return []

    window_start = as_of - timedelta(days=5)
    evidence: list[Evidence] = []
    for filing in index["filings"]:
        try:
            filed = date.fromisoformat(filing["filing_date"])
        except (TypeError, ValueError):
            continue
        if not (window_start <= filed <= as_of):
            continue
        evidence.append(
            Evidence(
                kind="filing",
                title=f"{ticker} filed a {filing['form']} on {filing['filing_date']}",
                detail=(
                    f"{filing['form_label']}: {filing['form_plain_english']} "
                    "A filing this close to the move is a concrete, checkable event — read it yourself."
                ),
                source="SEC EDGAR",
                source_url=filing["document_url"],
                numbers={"form": filing["form"], "filed": filing["filing_date"]},
            )
        )
        if len(evidence) >= 3:
            break
    return evidence


def _attribution(change_pct: float, stats: dict[str, Any]) -> dict[str, Any] | None:
    """Split the move into market, sector, and company-specific components.

    A deliberately simple one-factor decomposition: the market median stands in
    for the market factor, and the sector median's excess over the market stands
    in for the industry factor. Whatever is left is company-specific.
    """
    market = stats.get("market_median_pct")
    sector = stats.get("sector_median_pct")
    if market is None:
        return None

    sector_excess = round((sector - market), 3) if sector is not None else 0.0
    company = round(change_pct - market - sector_excess, 3)
    total = abs(market) + abs(sector_excess) + abs(company)
    if total == 0:
        return None

    def share(part: float) -> int:
        return round(abs(part) / total * 100)

    dominant = max(
        (("market", abs(market)), ("sector", abs(sector_excess)), ("company", abs(company))),
        key=lambda pair: pair[1],
    )[0]
    plain = {
        "market": "Most of today's move looks like the whole market moving, not this company specifically.",
        "sector": "Most of today's move looks like an industry-wide move rather than company-specific news.",
        "company": "Most of today's move looks specific to this company rather than the market or its industry.",
    }[dominant]

    return {
        "total_pct": round(change_pct, 3),
        "market_pct": market,
        "sector_excess_pct": sector_excess,
        "company_specific_pct": company,
        "shares": {
            "market": share(market),
            "sector": share(sector_excess),
            "company": share(company),
        },
        "dominant": dominant,
        "plain_english": plain,
        "method": (
            "One-factor decomposition: market = median move of all covered S&P 500 names; "
            "sector = median move of same-sector peers in excess of the market; "
            "company-specific = the remainder. This is an approximation, not a regression-based factor model."
        ),
    }


def deterministic_narrative(
    ticker: str,
    company_name: str,
    change_pct: float,
    attribution: dict[str, Any] | None,
    evidence: list[Evidence],
) -> str:
    """A defensible summary built purely from the computed evidence.

    This is what the app shows when no AI provider is configured, so the feature
    never depends on a model being available and never invents a cause.
    """
    parts = [f"{company_name} ({ticker}) moved {_fmt(change_pct)}."]

    if attribution:
        parts.append(attribution["plain_english"])
        parts.append(
            f"Roughly {attribution['shares']['market']}% of the size of the move lines up with the broad market, "
            f"{attribution['shares']['sector']}% with its industry, and "
            f"{attribution['shares']['company']}% is specific to the company."
        )

    vol = next((e for e in evidence if e.kind == "volatility"), None)
    if vol:
        parts.append(vol.detail)

    filings = [e for e in evidence if e.kind == "filing"]
    if filings:
        parts.append(
            "There "
            + ("is a" if len(filings) == 1 else f"are {len(filings)}")
            + " recent SEC filing"
            + ("" if len(filings) == 1 else "s")
            + " within a few days of this move: "
            + ", ".join(f"{e.numbers['form']} on {e.numbers['filed']}" for e in filings)
            + ". That is the most concrete place to look for a company-specific cause."
        )
    else:
        parts.append(
            "No SEC filing landed within five days of this move, so there is no obvious "
            "company-disclosed trigger in the public record."
        )

    parts.append(
        "This is an evidence summary, not a proven cause. Daily price moves often have no single explanation."
    )
    return " ".join(parts)


async def gather(
    db: AsyncSession,
    company: Company,
    change_pct: float,
    as_of: date,
) -> dict[str, Any]:
    evidence: list[Evidence] = []

    market_evidence, stats = await _market_context(db, company.ticker, company.sector)
    evidence.extend(market_evidence)

    vol_evidence, vol_stats = await _volatility_context(db, company.ticker, change_pct)
    if vol_evidence:
        evidence.append(vol_evidence)
        stats.update(vol_stats)

    evidence.extend(await _filing_context(company.ticker, as_of))
    evidence.extend(await _macro_context(db, as_of))

    attribution = _attribution(change_pct, stats)

    return {
        "evidence": [e.as_dict() for e in evidence],
        "attribution": attribution,
        "stats": stats,
        "narrative": deterministic_narrative(
            company.ticker, company.name, change_pct, attribution, evidence
        ),
    }


def to_prompt(company_name: str, ticker: str, change_pct: float, as_of: str, bundle: dict[str, Any]) -> str:
    lines = [
        f"{company_name} ({ticker}) moved {_fmt(change_pct)} on {as_of}.",
        "",
        "VERIFIED EVIDENCE (this is the only information you may use):",
    ]
    attribution = bundle.get("attribution")
    if attribution:
        lines.append(
            f"- Move decomposition: market component {attribution['market_pct']:+.2f}%, "
            f"sector component {attribution['sector_excess_pct']:+.2f}%, "
            f"company-specific component {attribution['company_specific_pct']:+.2f}%. "
            f"Dominant factor: {attribution['dominant']}."
        )
    for item in bundle["evidence"]:
        lines.append(f"- [{item['kind']}] {item['title']}: {item['detail']}")
    if not bundle["evidence"]:
        lines.append("- No evidence could be gathered.")

    lines += [
        "",
        "Write a plain-English explanation for a complete beginner, following these rules strictly:",
        "1. Use ONLY the evidence above. Do not mention any news, product launch, analyst action,",
        "   or event that does not appear in the evidence. If the evidence does not explain the move,",
        "   say plainly that it does not.",
        "2. Lead with whether this was mostly a market move, an industry move, or company-specific.",
        "3. If the move is statistically ordinary, say so and warn against reading a story into noise.",
        "4. No investment advice. Hedge causal claims (likely, consistent with, may reflect).",
        "",
        'Return JSON: {"narrative": string (120-180 words), "drivers": [{"title": string,',
        '"explanation": string, "confidence": 0-100, "hedge": string}]}. Each driver must map to a',
        "piece of evidence above. Confidence should reflect how directly the evidence supports it.",
    ]
    return "\n".join(lines)
